- name: Deploy QuickSite
  hosts: localhost
  tasks:
    - name: Pull latest code
      git:
        repo: 'https://github.com/yash-sewak07/FIS_DevOps_Training_YS.git'
        dest: '/root/FIS_DevOps_Training_YS/playbooks'
    - name: Install dependencies
      shell: npm install
      args:
        chdir: /root
    - name: Restart application
      shell: pkill node; nohup node /root/app.js &
